trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: tag
    displayName: 'Image tag'
    type: string
    default: 'latest'

jobs:
  - job:
    displayName: Container Build and Deploy
    steps:
      - checkout: self
        displayName: Repository checkout

      - task: DockerInstaller@0
        displayName: 'Install Docker'
        inputs:
          dockerVersion: '26.0.0'
        
      - task: Docker@2
        displayName: 'Build an image'
        inputs:
          command: 'build'
          repository: 'bestrongacrrestico.azurecr.io/bestrong-webapisample'
          Dockerfile: Dockerfile
          tags: ${{ parameters.tag }}

      - task: Docker@2
        condition: or(eq(variables['Build.Reason'], 'BatchedCI'), eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.Reason'], 'Manual'))
        displayName: 'Push an image'
        inputs:
          command: 'push'
          repository: 'bestrong-webapisample'
          tags: ${{ parameters.tag }}
          containerRegistry: bestrongacrrestico

      - task: AzureWebAppContainer@1
        condition: or(eq(variables['Build.Reason'], 'BatchedCI'), eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.Reason'], 'Manual'))
        displayName: 'Azure Web App on Container Deploy'
        inputs:
          azureSubscription: bestrong-wif-connect
          appName: web-app-bestrong-francecentral
          containers: bestrongacrrestico.azurecr.io/bestrong-webapisample:${{parameters.tag}}
          containerCommand: dotnet SampleWebApiAspNetCore.dll
      