trigger: none

pr:
  - main

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: tag
    displayName: 'Image tag'
    type: string
    default: 'latest'
  - name: image
    displayName: "Image name"
    type: string
    default: bestrong-webapisample
  - name: registry
    displayName: "Registry URL"
    type: string
    default: bestrongacrrestico.azurecr.io
  - name: deploy
    displayName: "Deploy to Azure Web App"
    type: boolean
    default: true
    values:
      - true
      - false
  - name: appName
    displayName: "App Service Name"
    type: string
    default: bestrong-webapp-francecentral

jobs:
  - job:
    displayName: Container Build and Deploy
    steps:
      - checkout: self
        displayName: Repository checkout

      - task: DockerInstaller@0
        displayName: 'Install Docker'
        inputs:
          dockerVersion: '26.0.0'
        
      - task: Docker@2
        displayName: 'Build an image'
        inputs:
          command: 'build'
          repository: '${{parameters.registry}}/${{parameters.image}}'
          Dockerfile: Dockerfile
          tags: ${{ parameters.tag }}

      - task: Docker@2
        condition: eq(${{parameters.deploy}}, True)
        displayName: 'Push an image'
        inputs:
          command: 'push'
          repository: '${{parameters.image}}'
          tags: ${{ parameters.tag }}
          containerRegistry: bestrongacrresticosc

      - task: AzureWebAppContainer@1
        condition: 'eq(${{parameters.deploy}}, True)'
        displayName: 'Azure Web App on Container Deploy'
        inputs:
          azureSubscription: bestrong-wif-connect
          appName: ${{parameters.appName}}
          containers: ${{parameters.registry}}/${{parameters.image}}:${{parameters.tag}}
      